name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'

      - name: Build
        run: cargo build --release

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      - name: Format with rustfmt
        run: cargo fmt -- --check

      - name: Run Tests
        run: cargo test
